version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    working_directory: ~/RS_Dev

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install react-simple-chatbot --save

  test:
    docker:
      - image: circleci/node:14

    working_directory: ~/RS_Dev

    steps:
      - checkout

      - run:
          name: Run Mocha tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - main
